# Site
repository: ia/modern-resume-theme
favicon: images/srv.ico


# Content configuration version
version: 2


# Personal info
name: HomeLab
title: Research & Development
#email: no-spam-please-no-please-no
#website: https://github.com/ia/modern-resume-theme


# Dark Mode (true/false/never)
darkmode: true


# Social links
github_username: h0melab


# About Section
about_title: Spheres of Research
#?about_profile_image: images/profile.jpg
about_content: |

  Our work is related (but not limited) to:
  - Embedded Hardware;
  - Firmware & System Software;
  - Wide range of Operating Systems;
  - Storage solutions & architecture of FileSystems;
  - Network technologies & Security;
  - Wireless, Radio, Signals.  
    



  **DISCLAIMER:** _HomeLab_ is not affiliated in any way with any commercial or corporate entity.  


content:
  - title: Writeups
    layout: list
    content:
      - layout: top-middle
        title: Coming Soon...
        link: https://github.com/h0melab/TBA
        additional_links:
          - title:  [tooltip]
            icon: fab fa-github
            url: https://github.com/h0melab
        quote: >
          Research in progress...
        description: |
          Stay tuned.


  - title: Setup
    layout: text
    content: |
      - uWorkbench:  

      ![miniworkbench](/images/homelab.jpg)


# Footer
footer_show_references: true
references_title: Copyleft Â© 2024 (some rights reserved) // CC BY-NC-ND 2.0 unless stated otherwise.


# Build settings
remote_theme: ia/modern-resume-theme


sass:
  sass_dir: _sass
  style: compressed


#plugins:
# - jekyll-seo-tag
